### ISSUE TITLE
outdated README?

### ISSUE THREAD

**Issue by karissa** [digidem/osm-p2p-syncfile#12]
the readme doesn't seem to have an example for replicating media, and then looking at the tests I'm finding that the api is slightly different (replicateMedia and replicateData, for example)

**Comment by noffle** [comment]
Oops! You're right. I updated the readme to use the right API (`replicateData`)

**Comment by noffle** [comment]
Oh! And replicateMedia works the same way as replicateData -- both are just duplex streams.
