### ISSUE TITLE
Incorrect tarball on Windows

### ISSUE THREAD

**Issue by gmaclennan** [digidem/osm-p2p-syncfile#17]
When the osm-p2p-db.tar file is created on a Windows machine, the tarball is incorrect because the entries are stored with back-slashes (`\`) as path separators, rather than forward-slashes `/`, which they should be according to the tar spec.

This may create unexpected errors syncing between Linux/Mac and Windows.

I think it's best to switch to `tar-fs` for reading/writing files, since it also covers a lot of other unusual edge-cases with windows and permissions and file name encoding.

**Comment by noffle** [comment]
Do you have a small example tarball you could upload somewhere? (bonus points if it's small enough to just base64 encode here!)

**Comment by okdistribute** [comment]
yep tar-fs looks great. it uses tar-stream under the hood, so it will likely be a straightforward replacement

**Comment by noffle** [comment]
Fixed in https://github.com/digidem/osm-p2p-syncfile/pull/19

I'm down to use tar-fs for future stuff in this module, if it meets our needs and handles the OS-specific cases!
